version: '3'

services:

  proxy:
    command: [nginx, '-g', 'daemon off;']
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./env/production/dhparam.pem:/etc/ssl/certs/dhparam.pem"
      - "./env/production/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "letsencrypt-etc:/etc/letsencrypt"
      - "nginx-site-root:/usr/share/nginx/html"

  certbot:
    image: certbot/certbot
    command: --version
    volumes:
      - "letsencrypt-etc:/etc/letsencrypt"      # --config-dir
      - "letsencrypt-lib:/var/lib/letsencrypt"  # --work-dir
      - "letsencrypt-log:/var/log/letsencrypt"  # --logs-dir
      - "nginx-site-root:/data/letsencrypt"

  frontend:
    env_file:
      - env/production/.env
      - env/production/.env.secret

  app:
    env_file:
      - env/production/.env
      - env/production/.env.secret

  tasks:
    env_file:
      - env/production/.env
      - env/production/.env.secret

  scheduler:
    env_file:
      - env/production/.env
      - env/production/.env.secret

volumes:
  letsencrypt-etc: {}
  letsencrypt-lib: {}
  letsencrypt-log: {}
  nginx-site-root: {}
