version: '3'

services:

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - './frontend:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development

  flask:
    command: flask run --host=0.0.0.0
    build:
      context: .
      dockerfile: Dockerfile.flask
    ports:
      - '5000:5000'
    environment:
      - FLASK_APP=backend
      - FLASK_ENV=development

  db:
    image: postgres:10
