version: '3'

services:

  proxy:
    command: [nginx-debug, '-g', 'daemon off;']
    image: nginx
    ports:
      - "80:80"
    volumes:
      - "./env/development/nginx.conf:/etc/nginx/conf.d/default.conf"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - './frontend:/usr/src/app'
      - '/usr/src/app/node_modules'
    env_file:
      - env/development/.env
      - env/development/.env.secret

  flask:
    command: backend/wait-for-it db:5432 --timeout=30 -- flask run --host=0.0.0.0
    build:
      context: .
      dockerfile: Dockerfile.flask
    volumes:
      - './backend:/app/backend'
      - './ssl_checker:/app/ssl_checker'
    env_file:
      - env/development/.env
      - env/development/.env.secret

  db:
    image: postgres:10
    volumes:
      - 'db:/var/lib/postgresql/data'

  broker:
    image: rabbitmq:3
    hostname: broker

  tasks:
    command: backend/wait-for-it broker:5672 --timeout=30 -- dramatiq backend.jobs --watch .
    build:
      context: .
      dockerfile: Dockerfile.flask
    volumes:
      - './backend:/app/backend'
      - './ssl_checker:/app/ssl_checker'
    env_file:
      - env/development/.env
      - env/development/.env.secret

  scheduler:
    command: backend/wait-for-it broker:5672 --timeout=30 -- python -m backend.scheduler
    build:
      context: .
      dockerfile: Dockerfile.flask
    volumes:
      - './backend:/app/backend'
      - './ssl_checker:/app/ssl_checker'
    env_file:
      - env/development/.env
      - env/development/.env.secret

volumes:
  db: {}
