FROM node:10

RUN mkdir /usr/src/app
WORKDIR /usr/src/app

ENV PATH /usr/src/app/node_modules/.bin:$PATH

COPY frontend/package.json /usr/src/app/package.json
RUN yarn install

COPY frontend/ /usr/src/app

CMD ["yarn", "start"]
