FROM python:3.7

RUN mkdir /app
WORKDIR /app

COPY backend/requirements.txt /app/backend/requirements.txt
COPY ssl_checker/requirements.txt /app/ssl_checker/requirements.txt
RUN pip install -r /app/backend/requirements.txt -r /app/ssl_checker/requirements.txt

COPY backend /app/backend
COPY ssl_checker /app/ssl_checker
