FROM python:3.7

WORKDIR /root

RUN mkdir /app

COPY backend/wait-for-it /usr/local/bin

COPY backend/requirements.txt /app/backend/requirements.txt
RUN pip install -r /app/backend/requirements.txt

COPY backend /app/backend

RUN pip install --editable /app/backend/web
RUN pip install --editable /app/backend/ssl_checker
RUN pip install --editable /app/backend/persistence
RUN pip install --editable /app/backend/tasks
