FROM python:3.7

WORKDIR /root

RUN mkdir /app

COPY backend/wait-for-it /usr/local/bin

COPY backend/requirements.txt /app/backend/requirements.txt
COPY ssl_checker/requirements.txt /app/ssl_checker/requirements.txt
RUN pip install -r /app/backend/requirements.txt -r /app/ssl_checker/requirements.txt

COPY backend /app/backend
COPY ssl_checker /app/ssl_checker

RUN pip install --editable /app/backend/web
